# ROCKET QUERIES/MUATIONS

query getAllRockets{
  allRockets {
    id
    rocketId
    launchSet{
      id
      missionName
    }
  }
}

query getRocketByID{
  rocket{
    id
    rocketId
  }
}

mutation createRocket {
  createRocket(input: {
    rocketId: "BFR-1",
  }){
    rocket{
     	id
    	rocketId
      launchSet{
        id
        missionName
        flightNumber
      }
    }
  }
}

mutation updateRocket {
  updateRocket(id: 1, input: {
    rocketId: "falcon8"
  }){
    rocket{
     	id
    	rocketId
      launchSet{
        id
        missionName
        flightNumber
      }
    }
  }
}

mutation deleteRocket {
  deleteRocket(id: 7){
    ok
  }
}

# PAYLOAD QUERIES/MUTATIONS

query getAllPayloads{
  allPayloads{
    id
    payloadId
    rocket{
      id
      rocketId
    }
    noradSet{
      id
      noradId
    }
  }
}

query getPayloadByID {
  payload(id: 3){
    id
    payloadId
    rocket{
      id
      rocketId
    }
  }
}

mutation updatePayload {
  updatePayload(id: 1, input: {
    payloadId: "test",
    rocketId: 1,
  }){
    payload{
      id
      payloadId
      rocket{
        id
        rocketId
      }
    }
  }
}

mutation createPayload {
  createPayload(input: {
    payloadId: "test1",
    rocketId: 4
  })
  {
    payload{
      id
      payloadId
      rocket{
        id
        rocketId
      }
    }
  }
}

mutation deletePayload{
  deletePayload(id: 5){
    ok
  }
}


# LAUNCH QUERIES/MUTATIONS

query getLaunchByID{
  launch(id: 3){
    id
    launchSite{
      id
      siteId
      siteName
    }
    launchSuccess
    launchDateUnix
    flightNumber
    rocket{
      id
      rocketId
    }
  }
}

query getAllLaunches{
  allLaunches {
    id
    launchSite{
      id
      siteId
      siteName
    }
    launchSuccess
    launchDateUnix
    flightNumber
    rocket{
      id
      rocketId
    }
  }
}

mutation createLaunch {
  createLaunch(input: {
  rocketId:5, 
  flightNumber: 95,
  missionName: "Test Mission 1",
  launchSuccess: true,
  launchsiteId: 2,
  launchDateUnix: 1619121637
})
  {
    launch{
      id
      flightNumber
      missionName
      rocket{
        id
        rocketId
      }
      launchSite{
        id
        siteId
        siteName
      }
      launchSuccess
      launchDateUnix
    }
  }
}


mutation updateLaunch {
  updateLaunch(id: 5, input: {
    rocketId: 4,
    launchSuccess: false,
    flightNumber: 94
  }){
  	launch{
      id
      flightNumber
      missionName
      rocket{
        id
        rocketId
      }
    }
  }
}

mutation deleteLaunch {
  deleteLaunch(id: 6){
    ok
  }
}

