# Generated by Django 3.2 on 2021-04-20 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100)),
                ('site_name', models.CharField(max_length=100)),
                ('site_name_long', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Norad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norad_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_id', models.CharField(max_length=100)),
                ('norad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.norad')),
            ],
        ),
        migrations.CreateModel(
            name='Rocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rocket_id', models.CharField(max_length=100)),
                ('payloads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.payload')),
            ],
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.PositiveIntegerField()),
                ('mission_name', models.CharField(max_length=100)),
                ('launch_date_unix', models.DateTimeField()),
                ('launch_success', models.BooleanField()),
                ('launch_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.launchsite')),
                ('rocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rocket')),
            ],
        ),
    ]
