# Generated by Django 3.2 on 2021-04-21 15:41

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='launch_date_unix',
            field=api.models.UCDateTimeField(),
        ),
    ]
