# Generated by Django 3.2 on 2021-04-21 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_launch_launch_date_unix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='norad_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.norad'),
        ),
    ]
