# Generated by Django 3.2 on 2021-04-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_payload_norad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norad',
            name='norad_id',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
