# Generated by Django 3.2 on 2021-04-22 02:52

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_norad_norad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='launch_date_unix',
            field=models.FloatField(default=time.time),
        ),
    ]
