# Generated by Django 3.2 on 2021-04-22 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210422_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launch',
            name='rocket',
        ),
        migrations.RemoveField(
            model_name='payload',
            name='norad_id',
        ),
        migrations.RemoveField(
            model_name='rocket',
            name='payloads',
        ),
        migrations.AddField(
            model_name='norad',
            name='payload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.payload'),
        ),
        migrations.AddField(
            model_name='payload',
            name='rocket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rocket'),
        ),
        migrations.AddField(
            model_name='rocket',
            name='launch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.launch'),
        ),
    ]
