# Generated by Django 3.2 on 2021-04-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210422_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='flight_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
