# Generated by Django 3.2 on 2021-04-23 01:16

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_launch_flight_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='launch_date_unix',
            field=models.FloatField(blank=True, default=time.time),
        ),
        migrations.AlterField(
            model_name='launch',
            name='mission_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
